AUTO_RESUME: true
CUDNN:
  BENCHMARK: false
  DETERMINISTIC: true
  ENABLED: true
GPUS: (0,)
SEED: 24

RECORD_BASE: './record/only_complete_600x1200_obj_det/kfold_inner_random_oc' #'/home/jd0617/Saved/cls_by_patient/rgb' '/tmp/testestes' # 
OUTPUT_DIR: 'result_single/frcnn' #retinanet

K_FOLD: 5
VAL_K_FOLD: 3
RESUME_K: 3 # idx start from 0
RESUME_INNER_K: 0 # idx start from 0
DATALOADER:
  NUM_WORKERS: 4

DATASETS:
  DATASET: CompletePatch # CellByPatient
  IMG_DIR: "/workspace/datasets/seg_by_patient/preprocessed/pos_cropped_patch_all_r1_r2"
  ANNO_DIR: "/workspace/datasets/seg_by_patient/preprocessed/anno/coco_format/pre_all_complete_merge.json"
  TRAIN_ANNO_DIR: '/workspace/datasets/seg_by_patient/preprocessed/anno/coco_format/pre_all_complete_train.json'
  TEST_ANNO_DIR: '/workspace/datasets/seg_by_patient/preprocessed/anno/coco_format/pre_all_complete_test.json'
  TRAIN: ('my_train', )
  TEST: ('my_test', )
  SHUFFLE: true
  KFOLD_LIST: '' #'/home/jd0617/Datasets_Models/Datasets/seg_by_patient/anno/k5_v3_patient_list.json' 

INPUT:
  MIN_SIZE_TRAIN: (600, )
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
  RANDOM_FLIP: 'none'
  CROP:
    ENABLED: False
  FORMAT: 'RGB'
  MASK_FORMAT: "bitmask" #"polygon"

MODEL:
  INIT_WEIGHTS: true
  # META_ARCHITECTURE: faster_rcnn_R_50_C4_1x
  PRETRAINED: ''
  PRETRAINED_STRICT: False
  MASK_ON: False
  MASK_SHAPE: [150, 300]
  MINMAX: True
  NUM_MASKS: 15
  FROM_LOGITS: True
  ALIGN_CORNERS: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 240 # 16*15
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.05
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  EXTRA:
    PRETRAINED_LAYERS:
      - 'conv1'
      - 'bn1'
      - 'conv2'
      - 'bn2'
      - 'layer1'
      - 'transition1'
      - 'stage2'
      - 'transition2'
      - 'stage3'
      - 'transition3'
      - 'stage4'  
    # FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      FUSE_METHOD: SUM

# LOSS:
#   LOSS: DiceLossWithBCE
#   REDUCTION: mean
#   ALPHA: 0.5
#   BETA: 0.5
#   GAMMA: 2.0
#   SMOOTH: 1e-6
#   DICE_RAT: 1.0

TRAIN:
  BATCH_SIZE_PER_GPU: 16
  OPTIMIZER: adam
  LR: 0.002 # 0.002 for normal, 0.0002 for smaller dataset
  LR_FACTOR: 0.1
  LR_STEP:
  - 96 # 64
  - 110 # 75
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false

TEST:
  BATCH_SIZE_PER_GPU: 16
  TEST_MODEL_FILE: ''
  EVAL_PERIOD: 0 # MAX_ITER // num_epochs

DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_RESULTS: true
  SAVE_EMBED_VIS: true

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  MAX_ITER: 1373 # (num_samples / batch_size) × num_epochs
  EPOCHS: 50
  LR_SCHEDULER_NAME : "WarmupMultiStepLR"
  WARMUP_ITERS: 130
  MOMENTUM : 0.9
  NESTEROV : False
  WEIGHT_DECAY : 0.0001
  WEIGHT_DECAY_NORM : 0.0
  GAMMA : 0.1
  STEPS : (829, 1098)
  CHECKPOINT_PERIOD : 200
  REFERENCE_WORLD_SIZE : 1
  BIAS_LR_FACTOR : 1.0
  WEIGHT_DECAY_BIAS : None  # None means following WEIGHT_DECAY
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE : "value"
    CLIP_VALUE : 1.0
    NORM_TYPE : 2.0
  AMP: 
    ENABLED: False